const HUMAN="X",AI="O",EMPTY="";
const WINNING_LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
let board=Array(9).fill(EMPTY),gameOver=false;
const boardElement=document.getElementById("board"),statusElement=document.getElementById("status"),algorithmElement=document.getElementById("algorithm"),resetButton=document.getElementById("resetBtn"),musicButton=document.getElementById("musicBtn"),nodesVisitedElement=document.getElementById("nodesVisited"),maxDepthElement=document.getElementById("maxDepth"),terminalStatesElement=document.getElementById("terminalStates"),prunedBranchesElement=document.getElementById("prunedBranches"),bestScoreElement=document.getElementById("bestScore"),algorithmDescriptionElement=document.getElementById("algorithmDescription");

function createBoardUI(){boardElement.innerHTML="";board.forEach((_,index)=>{const b=document.createElement("button");b.className="cell";b.dataset.index=index;b.setAttribute("aria-label",`Ô ${index+1}`);b.addEventListener("click",handleHumanMove);boardElement.appendChild(b)});render()}
function render(lastIndex=null){[...boardElement.children].forEach((cell,index)=>{cell.textContent=board[index];cell.classList.toggle("x",board[index]===HUMAN);cell.classList.toggle("o",board[index]===AI);cell.disabled=gameOver||board[index]!==EMPTY;if(index===lastIndex){cell.classList.remove("hit");void cell.offsetWidth;cell.classList.add("hit")}})}
function handleHumanMove(event){if(gameOver)return;startMusicAfterInteraction();const index=Number(event.currentTarget.dataset.index);if(board[index]!==EMPTY)return;board[index]=HUMAN;playMoveSound("human");render(index);if(finishIfNeeded())return;statusElement.textContent="AI đang quét cây trạng thái...";setTimeout(()=>{const aiIndex=makeAIMove();render(aiIndex);finishIfNeeded();if(!gameOver)statusElement.textContent="Lượt của bạn (X)"},260)}
function makeAIMove(){const algorithm=algorithmElement.value,stats={nodesVisited:0,maxDepth:0,terminalStates:0,prunedBranches:0};let result;if(algorithm==="dfs")result=findMoveDFSDemo(board,stats);else if(algorithm==="alphabeta")result=findBestMoveAlphaBeta(board,stats);else result=findBestMoveMinimax(board,stats);if(result.index!==null){board[result.index]=AI;playMoveSound("ai")}nodesVisitedElement.textContent=stats.nodesVisited;maxDepthElement.textContent=stats.maxDepth;terminalStatesElement.textContent=stats.terminalStates;prunedBranchesElement.textContent=stats.prunedBranches;bestScoreElement.textContent=result.score===null?"N/A":result.score;return result.index}

// DFS: chọn -> đi sâu -> quay lui
function dfsExplore(currentBoard,isAITurn,depth,stats){stats.nodesVisited++;stats.maxDepth=Math.max(stats.maxDepth,depth);const winner=getWinner(currentBoard),moves=getAvailableMoves(currentBoard);if(winner!==null||moves.length===0){stats.terminalStates++;return}for(const index of moves){currentBoard[index]=isAITurn?AI:HUMAN;dfsExplore(currentBoard,!isAITurn,depth+1,stats);currentBoard[index]=EMPTY}}
function findMoveDFSDemo(currentBoard,stats){dfsExplore(currentBoard,true,0,stats);const moves=getAvailableMoves(currentBoard);return moves.length===0?{index:null,score:null}:{index:moves[0],score:null}}

// MINIMAX
function findBestMoveMinimax(currentBoard,stats){let bestScore=-Infinity,bestIndex=null;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=AI;const score=minimax(currentBoard,0,false,stats);currentBoard[index]=EMPTY;if(score>bestScore){bestScore=score;bestIndex=index}}return{index:bestIndex,score:bestScore}}
function minimax(currentBoard,depth,isMaximizing,stats){stats.nodesVisited++;stats.maxDepth=Math.max(stats.maxDepth,depth);const terminalScore=evaluateTerminal(currentBoard,depth);if(terminalScore!==null){stats.terminalStates++;return terminalScore}if(isMaximizing){let bestScore=-Infinity;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=AI;const score=minimax(currentBoard,depth+1,false,stats);currentBoard[index]=EMPTY;bestScore=Math.max(bestScore,score)}return bestScore}let bestScore=Infinity;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=HUMAN;const score=minimax(currentBoard,depth+1,true,stats);currentBoard[index]=EMPTY;bestScore=Math.min(bestScore,score)}return bestScore}

// ALPHA-BETA
function findBestMoveAlphaBeta(currentBoard,stats){let bestScore=-Infinity,bestIndex=null,alpha=-Infinity;const beta=Infinity;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=AI;const score=alphaBeta(currentBoard,0,false,alpha,beta,stats);currentBoard[index]=EMPTY;if(score>bestScore){bestScore=score;bestIndex=index}alpha=Math.max(alpha,bestScore)}return{index:bestIndex,score:bestScore}}
function alphaBeta(currentBoard,depth,isMaximizing,alpha,beta,stats){stats.nodesVisited++;stats.maxDepth=Math.max(stats.maxDepth,depth);const terminalScore=evaluateTerminal(currentBoard,depth);if(terminalScore!==null){stats.terminalStates++;return terminalScore}if(isMaximizing){let bestScore=-Infinity;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=AI;const score=alphaBeta(currentBoard,depth+1,false,alpha,beta,stats);currentBoard[index]=EMPTY;bestScore=Math.max(bestScore,score);alpha=Math.max(alpha,bestScore);if(beta<=alpha){stats.prunedBranches++;break}}return bestScore}let bestScore=Infinity;for(const index of getAvailableMoves(currentBoard)){currentBoard[index]=HUMAN;const score=alphaBeta(currentBoard,depth+1,true,alpha,beta,stats);currentBoard[index]=EMPTY;bestScore=Math.min(bestScore,score);beta=Math.min(beta,bestScore);if(beta<=alpha){stats.prunedBranches++;break}}return bestScore}

function evaluateTerminal(currentBoard,depth){const winner=getWinner(currentBoard);if(winner===AI)return 10-depth;if(winner===HUMAN)return depth-10;if(getAvailableMoves(currentBoard).length===0)return 0;return null}
function getWinner(currentBoard){for(const[a,b,c]of WINNING_LINES){if(currentBoard[a]!==EMPTY&&currentBoard[a]===currentBoard[b]&&currentBoard[a]===currentBoard[c])return currentBoard[a]}return null}
function getAvailableMoves(currentBoard){const moves=[];currentBoard.forEach((value,index)=>{if(value===EMPTY)moves.push(index)});return moves}
function finishIfNeeded(){const winner=getWinner(board);if(winner===HUMAN){gameOver=true;statusElement.textContent="BẠN CHIẾN THẮNG!";statusElement.classList.add("win");createWinBurst("#ff8a3d");playWinSound();return true}if(winner===AI){gameOver=true;statusElement.textContent="AI CHIẾN THẮNG!";statusElement.classList.add("win");createWinBurst("#4de8ff");playWinSound();return true}if(getAvailableMoves(board).length===0){gameOver=true;statusElement.textContent="HÒA! HAI BÊN NGANG TÀI.";statusElement.classList.add("win");createWinBurst("#8b5cf6");return true}return false}
function resetGame(){board=Array(9).fill(EMPTY);gameOver=false;statusElement.classList.remove("win");nodesVisitedElement.textContent="0";maxDepthElement.textContent="0";terminalStatesElement.textContent="0";prunedBranchesElement.textContent="0";bestScoreElement.textContent="-";statusElement.textContent="Lượt của bạn (X)";updateAlgorithmDescription();render()}
function updateAlgorithmDescription(){const a=algorithmElement.value;if(a==="dfs")algorithmDescriptionElement.textContent="DFS Demo duyệt cây theo chiều sâu: chọn → đi sâu → gặp điểm dừng → quay lui. DFS không tự đánh giá nước đi.";else if(a==="minimax")algorithmDescriptionElement.textContent="Minimax dùng DFS để duyệt cây. AI là MAX chọn điểm lớn nhất, người chơi là MIN chọn điểm nhỏ nhất.";else algorithmDescriptionElement.textContent="Alpha-Beta giữ nguyên logic Minimax nhưng dùng alpha/beta để cắt các nhánh không thể thay đổi quyết định."}

// STARFIELD
const starCanvas=document.getElementById("starfield"),starCtx=starCanvas.getContext("2d");let stars=[];function resizeStarfield(){starCanvas.width=innerWidth;starCanvas.height=innerHeight;const count=Math.min(220,Math.floor(innerWidth*innerHeight/6500));stars=Array.from({length:count},()=>({x:Math.random()*starCanvas.width,y:Math.random()*starCanvas.height,r:Math.random()*1.5+.2,speed:Math.random()*.28+.04,alpha:Math.random()*.7+.2}))}function animateStars(){starCtx.clearRect(0,0,starCanvas.width,starCanvas.height);for(const s of stars){s.y+=s.speed;if(s.y>starCanvas.height){s.y=0;s.x=Math.random()*starCanvas.width}starCtx.beginPath();starCtx.arc(s.x,s.y,s.r,0,Math.PI*2);starCtx.fillStyle=`rgba(255,255,255,${s.alpha})`;starCtx.fill()}requestAnimationFrame(animateStars)}addEventListener("resize",resizeStarfield);resizeStarfield();animateStars();

// WIN PARTICLES
function createWinBurst(color){const burst=document.getElementById("winBurst");burst.innerHTML="";for(let i=0;i<32;i++){const p=document.createElement("span");p.className="particle";p.style.color=color;const angle=Math.random()*Math.PI*2,distance=90+Math.random()*220;p.style.setProperty("--dx",`${Math.cos(angle)*distance}px`);p.style.setProperty("--dy",`${Math.sin(angle)*distance}px`);burst.appendChild(p)}setTimeout(()=>burst.innerHTML="",1000)}

// WEB AUDIO AMBIENT MUSIC + SFX
let audioContext=null,masterGain=null,ambientGain=null,musicEnabled=false;
function ensureAudio(){if(audioContext)return;audioContext=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioContext.createGain();masterGain.gain.value=.34;masterGain.connect(audioContext.destination);ambientGain=audioContext.createGain();ambientGain.gain.value=0;ambientGain.connect(masterGain);const filter=audioContext.createBiquadFilter();filter.type="lowpass";filter.frequency.value=780;filter.Q.value=.7;filter.connect(ambientGain);[110,164.81,220].forEach((frequency,index)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=index===1?"triangle":"sine";oscillator.frequency.value=frequency;gain.gain.value=.04;oscillator.connect(gain);gain.connect(filter);oscillator.start()})}
function setMusic(enabled){ensureAudio();musicEnabled=enabled;const now=audioContext.currentTime;ambientGain.gain.cancelScheduledValues(now);ambientGain.gain.setTargetAtTime(enabled?.48:0,now,.35);musicButton.textContent=enabled?"♫ NHẠC: BẬT":"♫ NHẠC: TẮT"}
function startMusicAfterInteraction(){ensureAudio();if(audioContext.state==="suspended")audioContext.resume();if(!musicEnabled)setMusic(true)}
musicButton.addEventListener("click",()=>{ensureAudio();if(audioContext.state==="suspended")audioContext.resume();setMusic(!musicEnabled)})
function playTone(frequency,duration,type="sine",volume=.12){ensureAudio();const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=type;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);oscillator.connect(gain);gain.connect(masterGain);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}
function playMoveSound(side){if(side==="human"){playTone(260,.18,"triangle",.10);setTimeout(()=>playTone(340,.14,"sine",.07),45)}else{playTone(420,.18,"sine",.10);setTimeout(()=>playTone(620,.14,"triangle",.06),45)}}
function playWinSound(){[440,554.37,659.25,880].forEach((n,i)=>setTimeout(()=>playTone(n,.35,"sine",.10),i*100))}

resetButton.addEventListener("click",()=>{startMusicAfterInteraction();resetGame()});
algorithmElement.addEventListener("change",resetGame);
updateAlgorithmDescription();createBoardUI();
